export CUDA_ROOT=/usr/local/cuda-9.2/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-9.2/lib64:/usr/local/cuda-9.2/extras/CUPT/lib64

echo "Running the python script now!"
echo ""

CUDA_VISIBLE_DEVICES='' python3 gzoo_neuralnet.py

echo ""
echo "Bash file is complete!"
